### PR TITLE
add "--lsp" flag to bsc to start an LSP server

### PR DESCRIPTION
**Pull request by ZeeD**
I'm not sure this is the best approach. Please suggest a better integration - my real doubt is that almost no flow is shared between the LSP and the °normal° bsc functionality

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
Yeah, this is a bit more involved than I had intended. The primary reason for wanting to use something like `--lsp` was so we could keep the same entry point instead of exposing a whole separate binary name (like `npx bsc-lsp`). You can run programs without even installing them by using their full name. Like this: `npx brighterscript --lsp` it will download the package right then, and then spin it up and use it. 

In the CLI, we have full control over how we run the code, so I was envisioning something more like this:

```typescript
//cli.ts
let options = yargs
    // ...
   .option('lsp', { type: 'boolean', defaultDescription: 'false', description: 'Run brighterscript as a language server.' })
   .argv;

if (options.lsp === true) {
     const server = new LanguageServer();
     server.run();
} else{
    let builder = new ProgramBuilder();
    // ...


```

**Comment by ZeeD** [comment]
I changed the PR following your suggestions

**Comment by TwitchBronBron** [comment]
Looks great! Did you have a chance to test this against your Eclipse implementation to verify that it works?

**Comment by ZeeD** [comment]
yes, it works as expected!

**Comment by TwitchBronBron** [comment]
This change has been included in release v0.56.0

**Pull request merged**
