### PR TITLE
Adds UniversalFunctionType for functions as params.

### LINKED ISSUE #516: `as function` doesn't support parameters
This produces an error. I believe that `as Function` should include all function permutations (any params, any return type, void return type). 

```typescript
it('allows `Function` to have zero or more parameters', () => {
    program.setFile('source/main.brs', `
        sub callFuncWithParam(func as Function, value)
            func(value)
        end sub

        sub printValue(value)
            print value
        end sub

        sub main()
            callFuncWithParam(printValue, "hello world")
        end sub
    `);

    program.validate();
    expectZeroDiagnostics(program);
});
```

image

### PR DESCRIPTION
**Pull request by markwpearce**
Fixes #516 and #517

### CODE REVIEW

**Comment by markwpearce** [comment]
- [ ] Add test for using return type from a function provided as a parameter
- [ ] Add test for using return type from a function provided as a parameter in an assignement

**Comment by markwpearce** [comment]
Another approach is to just have one FunctionType but have a `isGeneric` flag on the constructor. Pros of this approach is that really, the type defined `as Function` is the same an actual function declaration.

**Comment by TwitchBronBron** [comment]
I'm struggling with the term `generic`, because we will eventually support [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html). What about something like `GeneralFunction`, `NonSpecificFunction`, `AllPurposeFunction`, `CatchallFunction`, `TopLevelFunction`. Any of those?

I'm leaning towards keeping your current design (separate dedicated type). It helps keep the current FunctionType logic a little cleaner. But I could be convinced either way. Thoughts?

**Comment by markwpearce** [comment]
I hear what you're saying about `GenericFunction` ... How about `UniversalFunction` 

I think the best way would be to have `UniversalFunctionType` extend `FunctionType`. `ReturnType` would always return Dynamic, and the `addParam` method would be noops.

Then the `isFunctionType` reflection function look for either `FunctionType` or `UniversalFunctionType`.

This way we don't need special case handling everywhere in the code.

**Review by TwitchBronBron — APPROVED** [review]

**Pull request merged**
